version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: tasktime
      POSTGRES_USER: tasktime
      POSTGRES_PASSWORD: tasktime
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tasktime"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: