version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: timetask-db
    environment:
      POSTGRES_DB: timetask
      POSTGRES_USER: timetask
      POSTGRES_PASSWORD: timetask
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timetask -d timetask"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: .
    container_name: timetask-server
    environment:
      DATABASE_URL: "postgres://timetask:timetask@postgres:5432/timetask?sslmode=disable"
      PORT: "8080"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: